#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'
require RAILS_ROOT + '/lib/jobs/logisto_worker'
Delayed::Worker.new(:min_priority => ENV['MIN_PRIORITY'], :max_priority => ENV['MAX_PRIORITY']).start
